# Generated by Django 3.1.1 on 2020-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
