# Generated by Django 3.1.1 on 2020-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankSearch', '0002_auto_20201217_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='branch',
            field=models.CharField(max_length=150),
        ),
    ]
